### ISSUE TITLE
Cant get integration working

### ISSUE THREAD

**Issue by erikkubica** [assistify/rcapps-gitlab#15]
Hi,

I have configured the webhook URL and the base URL, created channel and sent a test, it was not received in the channel. Tested multiple combinations of base URL and channel name:

Our GitLab URL is: https://gitlab.com/example.com/projectslug

So I have tried:

Base: https://gitlab.com/
Ch: example.com-projectSlug

Base: https://gitlab.com/example.com
Ch: projectSlug

Thanks

**Comment by jschirrmacher** [comment]
This might have something to do with case sensitivity. Pls try to name the channel in all lower case.

Also, I found that the newest version from this repository is not yet in the Marketplace. I triggered a new release, but this depends on an approval from Rocketchat to actually get there. It might be worth to look out for this coming release, and try with this version again.

**Comment by erikkubica** [comment]
@jschirrmacher sorry my bad, we had it lowercase everything I just wrote the example camel case. The problem was, that the hook url was like: example.com//api/apps/...  notice the double slash after .com maybe we have rocket chat miss-configured since it was generated with that double slash, usually that's no problem for routing in most apps so I did not give it too much thought.
